name: ICON to Google Drive

on:
  workflow_dispatch:
  schedule:
    - cron: "15 3 * * *"    # Alle 03:05 UTC ogni giorno
    #- cron: "0 5 * * *"    # Alle 05:00 UTC ogni giorno
    #- cron: "0 11 * * *"    # Alle 11:00 UTC ogni giorno
    - cron: "15 14 * * *"   # Alle 15:05 UTC ogni giorno
    #- cron: "0 17 * * *"   # Alle 17:00 UTC ogni giorno
    #- cron: "0 23 * * *"    # Alle 23:00 UTC ogni giorno

jobs:
  run-bollettino:
    runs-on: ubuntu-latest
    env:
      LC_ALL: it_IT.UTF-8
      LANG: it_IT.UTF-8
      LANGUAGE: it_IT.UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Italian locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen it_IT.UTF-8
          sudo update-locale LANG=it_IT.UTF-8

      - name: Run Python script
        env:
          R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
          R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        run: python first_guess_icon_v4git.py

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Setup rclone config from secret
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          mkdir -p /home/runner/.config/rclone
          echo "${RCLONE_CONFIG}" > /home/runner/.config/rclone/rclone.conf
          chmod 600 /home/runner/.config/rclone/rclone.conf

      - name: Upload output to Google Drive
        run: |
          RUN_FOLDER=$(date +%Y_%m_%d)
          rclone copy ./output/$RUN_FOLDER gd_personal:Previsioni-meteo_ICON/$RUN_FOLDER --drive-chunk-size 64M --verbose
